apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
      - name: demo-app
        env:
        - name: NODE_ENV
          value: "production"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=observability-prod,deployment.environment=production"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
