global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aiops-platform'
    environment: 'production'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['prod-otel-collector:8889']

  - job_name: 'demo-app'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - observability-prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: prod-demo-app
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        replacement: ${1}:3000
