apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
spec:
  template:
    spec:
      containers:
      - name: tempo
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
