global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aiops-demo'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'otel-collector'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

# Recording rules will be loaded from the rules directory
rule_files:
  - '/etc/prometheus/rules/*.yml'
